### PR TITLE
Add My1 key and 9.1.1 sig

### PR DESCRIPTION
**Pull request by My1**
pretty self explanatory

also side note built via Docker on Windows

### CODE REVIEW

**Comment by benma** [comment]
Great, thank you. 

Small inconsistency nit: `assertion-my1.sig` is lower case `my1`, but the gpg key is uppercase `My1`. Please make it the same

**Comment by My1** [comment]
fixed, guess I missed the shiftkey lol

**Review by benma — APPROVED** [review]

**Comment by benma** [comment]
Thanks, merged.

Fyi, for next time: you can squash commits and force-push to a branch to replace the commits in a PR, to keep clean git history.

**Comment by My1** [comment]
I did try to squash a bit using prs on the fork, but no idea how to force push on browser. But prs have the quite nifty squash and merge feature (dropdown next to merge button which can help even if not everyone squashes all properly.

**Pull request merged**
