### PR TITLE
rust/password: use heap allocation

### PR DESCRIPTION
**Pull request by benma**
Much better ergonomics and less copies.

### CODE REVIEW

**Review by x1ddos — COMMENTED** [review]
Don't need `clear` fn and `Drop` impl since Box will do it automatically?

Also, in `test_clear` would be better to just drop the `pw` and check that the value was cleared.

**Comment by benma** [comment]
> Don't need `clear` fn and `Drop` impl since Box will do it automatically?

Box will safely zero its contents on drop? I need a reference for that.

We should change it to use zeroize though, but that is a different matter.

**Comment by benma** [comment]
> > Don't need `clear` fn and `Drop` impl since Box will do it automatically?
> 
> Box will safely zero its contents on drop? I need a reference for that.
> 
> We should change it to use zeroize though, but that is a different matter.

Disproven in private chat y example ;)

**Comment by x1ddos** [comment]
> > > Don't need `clear` fn and `Drop` impl since Box will do it automatically?
> > 
> > 
> > Box will safely zero its contents on drop? I need a reference for that.
> > We should change it to use zeroize though, but that is a different matter.
> 
> Disproven in private chat by example ;)

Indeed! From our playground it turned out to clear only a few first elements.

**Review by x1ddos — APPROVED** [review]
LGTM

**Pull request merged**
