### PR TITLE
Multisig name on device

### PR DESCRIPTION
**Pull request by benma**
Can test by showing a multisig receive address in send_message, and when prompted for the name, submit the empty string.

### CODE REVIEW

**Comment by benma** [comment]
@x1ddos the user can easily enter an invalid name, e.g. an empty name or one that starts with whitespace, or is too long.

I will try to improve on this in another PR.

**Review by x1ddos — APPROVED** [review]
LGTM

> empty name or one that starts with whitespace, or is too long

whitespace shouldn't be a problem because `special_chars` is false in the passed params, right.

**Comment by benma** [comment]
> whitespace shouldn't be a problem because `special_chars` is false in the passed params, right.

hmm that was an oversight, meant to enable it. space would be good here right?

**Comment by x1ddos** [comment]
> > whitespace shouldn't be a problem because `special_chars` is false in the passed params, right.
> 
> hmm that was an oversight, meant to enable it. space would be good here right?

but then you would enable all other "special" characters. I'd keep it simple for now and leave as is. you did say you'll want to improve it against an empty name and other things anyway.

**Comment by x1ddos** [comment]
> > > whitespace shouldn't be a problem because `special_chars` is false in the passed params, right.
> > 
> > 
> > hmm that was an oversight, meant to enable it. space would be good here right?
> 
> but then you would enable all other "special" characters. I'd keep it simple for now and leave as is. you did say you'll want to improve it against an empty name and other things anyway.

ah well OTOH who cares what the users types in the name... unless it's propagated to the app and causes some panics :)

**Comment by benma** [comment]
I'll circle back to the special chars question later.

**Pull request merged**
