### PR TITLE
u2f: use Rust unlock/confirm workflows

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by benma** [comment]
This is a shortcut to get u2f to use the Rust workflows, without rewriting the whole message processor like we did for HWW.

The goal is to be able to delete the C workflows and workflow stack.

unlock is the first one, the only other one is `confirm()`, which can follow in another PR.

**Comment by benma** [comment]
Sth similar will be done in fido2 after https://github.com/digitalbitbox/bitbox02-firmware/pull/437/ is merged.

**Comment by benma** [comment]
Actually pushed another commit to do the same for the confirm workflow. After this PR, u2f does not use any C workflows anymore.

**Comment by x1ddos** [comment]
Nice. I have nothing to add. Let me just try it on a real device.

**Pull request merged**
