### PR TITLE
verifying firmware for Multi v9.15.0 and adding assertation

### PR DESCRIPTION
**Pull request by guggerf**
My GPG pub key is already in PR #1133

### CODE REVIEW

**Review by benma — CHANGES_REQUESTED** [review]
Thanks!

Please rebase this on master, otherwise CI will not pass due to the missing pubkey.

**Comment by benma** [comment]
@guggerf I think something went wrong with the rebase. There are now 5 commits instead of one. You can just apply your original commit on top of origin/master, or rebase it on origin/master., and force push it onto the same branch in your fork. Let me know if you need help.

**Comment by guggerf** [comment]
> @guggerf I think something went wrong with the rebase. There are now 5 commits instead of one. You can just apply your original commit on top of origin/master, or rebase it on origin/master., and force push it onto the same branch in your fork. Let me know if you need help.

Hmm I thought I did this. Well it seams that I need help ;-)

**Comment by thisconnect** [comment]
@guggerf I usually have the original as my fork and the original repo as "upstream" remote. so my `git remote -v` shows:
```
origin	git@github.com:thisconnect/bitbox02-firmware.git (fetch)
origin	git@github.com:thisconnect/bitbox02-firmware.git (push)
upstream	https://github.com/digitalbitbox/bitbox02-firmware.git (fetch)
upstream	https://github.com/digitalbitbox/bitbox02-firmware.git (push)
```

In this case you could just do `git fetch --all` and then `git rebase upstream/master` assuming you are on the branch you want to rebase. You can also rebase a local branch without checking it out first with `git rebase upstream/master verifyFirmwareMulti`. 

BTW. you don't have to use `upstream`, if you use `origin` as the original digitalbitbox/bitbox02-firmware repo then of corse you would use `git rebase origin/master verifyFirmwareMulti`, just whatever works for you. 

Taking  a look at the "network graph", it seems like there is merge commit, but I assume this would go away after you rebased. see:
  
Screen Shot 2023-10-02 at 11 15 12

 I'd expect one branch off of upstream master and then your commit.

https://github.com/digitalbitbox/bitbox02-firmware/network

btw. you can check this also locally with `git log --graph --oneline --all`.

or add a shortcut to your gitconfig do this commend with `git tree`
```
# ~/.gitconfig
[alias]
tree = log --graph --oneline --all
# usage on command line:
git tree
```

**Comment by guggerf** [comment]
@benma thank you so much.
I think I made the mistake to rebase the main and not the branch. But now it should be correct with only one commit.

Hoppefully next time I get it correct the first time ;-)

**Comment by thisconnect** [comment]
LGTM 👍

**Review by benma — APPROVED** [review]

**Pull request merged**
