### PR TITLE
Added hardware docs to readme

### PR DESCRIPTION
**Pull request by jadzeidan**
Added links to readme for the following documents:

- PCB schematics v2.1
- PCB bill of materials (BOM) v2.1
- PCB x-ray v2.1

### CODE REVIEW

**Comment by benma** [comment]
I think one commit is enough for those changes :smile:

**Comment by jadzeidan** [comment]
> I think one commit is enough for those changes 😄

Yeah, idk how to squash them...

**Comment by NickeZ** [comment]
> > I think one commit is enough for those changes smile
> 
> Yeah, idk how to squash them...

If you want to learn git in the terminal you run `git rebase -i master` and then mark all commits you want to squash with `s` (squash) or `f` (fixup). Otherwise there might be some gui tool you can download and do it in.

**Comment by jadzeidan** [comment]
ok created a new PR with squashed commits #281

**Pull request closed without merging**
