### PR TITLE
Rust stable

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by benma** [comment]
image

Uuh...

**Comment by x1ddos** [comment]
Ha! Abuse!? What abuse? :see_no_evil: 

Maybe we should really switch from travis to github workflows: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow. I'll try to play with it and see if it can work for us.

**Comment by benma** [comment]
Ran CI locally, got this in `make device-tests`:

```
[ 58%] Building C object test/device-test/CMakeFiles/fw_test_ssp.elf.dir/src/test_ssp.c.obj
[ 61%] Linking C executable ../../bin/fw_test_ssp.elf
/usr/local/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld: /usr/local/bin/../lib/gcc/arm-none-eabi/8.2.1/thumb/v7e-m+fp/softfp/libgcc.a(_arm_addsubdf3.o): in function `__aeabi_dsub':
(.text+0x8): multiple definition of `__aeabi_dsub'; ../../lib/libfirmware_rust_c.a(compiler_builtins-5829be534503bd8e.compiler_builtins.cthmhl66-cgu.175.rcgu.o):/cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.27/src/macros.rs:226: first defined here
```

@NickeZ any idea how to debug? :innocent:

**Comment by x1ddos** [comment]
Oh, I forgot to run the tests! Sorry.

`__aeabi_dsub` is coming from https://github.com/rust-lang/compiler-builtins/pull/349, I believe. Haven't tracked why device-tests are different yet either.

**Pull request merged**
