### PR TITLE
Firmware v9.13.0 verification

### PR DESCRIPTION
**Pull request by yaziza**

### CODE REVIEW

**Comment by benma** [comment]
Thanks a lot! Could you please sign your commit as well?

**Comment by benma** [comment]
@yaziza thanks but your commit signature is marked as unverified. Could you fix that?

**Comment by yaziza** [comment]
> @yaziza thanks but your commit signature is marked as unverified. Could you fix that?

will fix, it's because of GitHub email privacy settings ... (same for the other PR v9.14.0)

**Comment by yaziza** [comment]
commit signature updated.

**Comment by Beerosagos** [comment]
@benma sigs LGTM!

Thanks a lot!

**Pull request merged**
