### PR TITLE
BB02-4.1.0 assertions strnbrg

### PR DESCRIPTION
**Pull request by jstrnbrg**

### CODE REVIEW

**Comment by benma** [comment]
Thanks :pray:

**Comment by benma** [comment]
Please sign your commits so that this PR can be merged.

**Comment by jstrnbrg** [comment]
@benma signed

**Comment by jstrnbrg** [comment]
squashed into one commit and signed

**Comment by benma** [comment]
Thanks!

If you're up for it, please repeat it for v4.2.1 :)

**Pull request merged**
