### PR TITLE
staging -> master

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by x1ddos** [comment]
Going to flash this and try it out.

**Comment by benma** [comment]
Maybe merge it locally first and try it, just in case there is a semantic conflict. Probably not though.

**Comment by x1ddos** [comment]
Manually tested a few functionalities like transactions, backup and restore with the desktop app built from head to pick up https://github.com/digitalbitbox/bitbox02-api-go/pull/36.

All seem to work well thus far. I'll try and see if I can manage to run device-tests.

**Comment by x1ddos** [comment]
BTW, also verified commit hashes, just in case. All seem to match:

```
$ git cherry -v upstream/master upstream/staging-rust-async
+ e57688cb7742622ecaf120a42fa70ce90216c1ac rust/bitbox02: add zero-on-drop Password struct
+ 99911fd9c7bd872e1cc85b9cdfaeb142e924ff9b rust/bitbox02/util: add panicy str_to_cstr_force
+ 6fab8cb53c5805908b274673bca3609508815947 rust: whitelist some useful C functions
+ 2716710bfde73c72451ec56bb63ab1ddc7a1d771 rust/bitbox02: add safe wrappers for password and screen push/pop
+ eae7fca5cbc29dfa413fbe5604f7c5d9a0d3e20d bitbox02-rust: add async password_enter
+ 288c88ea99fd46b1a96dd2103cd9d4ecc4aa634b bitbox02-rust: add async confirm workflow
+ 263f091469b00efc20b10d8ba7f4ef56c9eb9d12 rust/ui: use callbacks in component
+ 10baaa6424ce6a02fefd7d9d6c69886e33f23a44 components/status: remove unused param `delay`
+ 5df9f88d7c724fe6a6b45cce39624c1870a2aaea rust: add async status display
+ 6dc53975da358de70397f198930e2a10edfb8810 rust/bitbox02/password: refactor, add tests
+ 9807ff877972612c5381cfa63f2ad32dda2fdd37 rust: add async unlock workflow
+ a5dd0769f18dc3cadb944df5e9056be9aef8b3e5 components/confirm: one callback instead of two
+ 5dadf24492c2be52e99b93e422dcf74ff3534782 rust/bitbox02/ui: sync label size with the C label component
+ 2a4627dbf8f6f8700af16c1915c777e242734efa rust/bitbox02/ui: properly clean up callbacks
+ 9e59235e33f9915a34f4fbecbd5baaf4397372ed hww: move actual api processing to new file
+ b49130615098e907a31b2ce8044a033079aba30a hww: turn api packet processor into a Rust async task
+ a8449201fb623bdd5599a7ff68296fe3a26ff944 workflow: remove now unused workflow_unlock_blocking()
+ 2995a0078a8b8e587ce4b682860aa5b61df71de5 rust/hww: cancel task after timeout
+ 292686154ba1c1f5a41661cded91986a80bf25b0 rust/async_usb: impl Sync to concentrate unsafe code in one place
+ c50b3b2fb0277d8a357a6127e79c054328299b02 rust/hww: port attestation api call
+ 8217e332d80d8d79be2458e09bcab4ff4d7af5fe rust/hww: fix unlock err code
+ cfe56207e130931cc7442f1942ed8736cc7ca626 rust/bitbox02: wrap random
+ 5c86c0996fc8bc25e0f8fc2f7b22dc7cb0033651 hww: move unlocked check to Rust
```

**Pull request merged**
