### PR TITLE
releases: add userofreddit44 pubkey assertion for v9.12.0

### PR DESCRIPTION
**Pull request by userofreddit44**
Reproduced firmware (multi-edition) v9.12.0 successfully.

### CODE REVIEW

**Review by benma — CHANGES_REQUESTED** [review]
Thanks for your contribution.

Please squash the two commits into one and put `releases: add userofreddit44 pubkey assertion for v9.12.0` in the title - the current commit titles are too generic.

Also, it seems that your git commits are signed with a different key. Could you use the same key for the git commit and the assertion signature?

**Comment by userofreddit44** [comment]
Sorry. I may or may not of squash-ed the commits correctly.

**Comment by benma** [comment]
> Sorry. I may or may not of squash-ed the commits correctly.

Yeah, now there are six commits instead of one :smile: Please try again to make only one commit.

**Comment by benma** [comment]
@userofreddit44 let me know if you need help with this. If git squashing etc. is too much trouble, you could make a new branch and add your changes again from a clean slate and open a new PR.

```
git checkout -b assertion origin/master
<apply changes>
git commit ... (use same key to sign the commit as you use to sign the assertion.txt)
```

**Comment by userofreddit44** [comment]
@benma Learning how to squash is still on my agenda, it's just a matter of when, I will let you know if I incur anything too problematic on my attempt/s so thanks, I will indeed close this PR as it looks like spaghetti.

**Pull request closed without merging**
