### PR TITLE
fonts/font_a_11X10: fix W

### PR DESCRIPTION
**Pull request by benma**
It had a cut off left arm.

### CODE REVIEW

**Comment by x1ddos** [comment]
But you have to tell me how you did it. Where's your famously handy script?

**Comment by benma** [comment]
> But you have to tell me how you did it. Where's your famously handy script?

you have been warned :joy: 

```Python
import pygame

pygame.init()

windowSurface = pygame.display.set_mode((500, 400), 0, 32)

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

windowSurface.fill(WHITE)

widths = [
    3,2,4,6,6,10,7,2,4,4,4,6,3,4,3,3,6,6,6,6,6,6,6,6,6,6,3,3,6,6,6,6,11,8,7,7,7,6,6,8,7,2,5,7,6,8,7,8,6,8,7,7,6,7,8,11,7,8,7,3,3,3,5,6,4,6,6,6,6,6,4,6,6,2,3,5,2,8,6,6,6,6,4,6,4,6,6,10,6,6,6,4,2,4,6,
    ]
char_height = 10
char_width = 11

bn = char_width
bn >>= 3
if char_width % 8:
    bn += 1
start_char = 32

bt = ord('W')
index = 0
letter = [0x10,0x02,0x28,0x02,0x29,0x01,0x29,0x01,0x45,0x01,0x45,0x01,0x82,0x00,0x82,0x00,0x00,0x00,0x00,0x00]
for i in range(char_height):
    i1 = 2*i
    i2 = 2*i + 1
    l = letter[i1]
    l <<= 1
    letter[i2] <<= 1
    if l > 0xFF:
        rest = l % 0xFF
        l &= 0xFF
        if rest:
            letter[i2] |= 0b01

    letter[i1] = l
letter[0] |= 0b0000001
letter[2] |= 0b0000001

print(list(map(lambda a: a.to_bytes(1,'big').hex(), letter)))

yo = 0
for j in range(char_height):
    xo = 0
    c = widths[55]
    for i in range(bn):
        b = letter[index]
        index += 1
        k = 0
        while k < 8 and c:
            pygame.draw.rect(windowSurface, GREEN if b & 0x01 else BLACK, pygame.Rect(xo*10, yo*10, 10, 10))
            b >>= 1
            xo += 1
            c -= 1
            k += 1
    yo += 1

pygame.display.update()

```

copy pasted some of the `W` constants and messed around with it until I understood the format. The loop in the middle is shifting the image to the right by 1px.

maybe some day it can be turned into a font editor :P

**Comment by NickeZ** [comment]
You actually wrote a script to print the character? Haha was that faster than just iterating with a test firmare? ;P

**Comment by x1ddos** [comment]
OMG drawing a character in pygame is amazing. I only added this at the bottom:

```python
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            exit()
```

otherwise, my pygame window would close right away.

We should add it somewhere to tools/ or py/ directory, please!

**Comment by benma** [comment]
> You actually wrote a script to print the character? Haha was that faster than just iterating with a test firmare? ;P

iteration speed is the most important! compiling and flashing even simple firmware takes many seconds, while iterating with the script is immediate :D

**Pull request merged**
