### PR TITLE
apps/eth: port transaction signing to Rust

### PR DESCRIPTION
**Pull request by benma**
Builds on top of https://github.com/digitalbitbox/bitbox02-firmware/pull/716

### CODE REVIEW

**Review by x1ddos — COMMENTED** [review]
Cool. What about the app_eth_sighash tests? Now that verify recipients are in rust, they can be stubbed in tests. Seems like it's the only sole ETH test in C.

**Review by x1ddos — APPROVED** [review]
LGTM but not sure what the plan is for app_eth_sighash tests in C.

**Comment by benma** [comment]
> LGTM but not sure what the plan is for app_eth_sighash tests in C.

The sighash impl is still in C, and its tests in C remain the implementation it is also ported to Rust.

**Comment by x1ddos** [comment]
Oh, true. I kind of missed that sighash impl is still in C. Never mind. :)

**Pull request merged**
