### PR TITLE
rust: update sha2 dep to v0.9.2

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by benma** [comment]
Also updated noise-rust-protocol, which bumped its own sha2 dep, so we only have use version of sha2.

**Comment by benma** [comment]
Still have some more "duplicate" deps, looking into them.

**Comment by benma** [comment]
Done, upgraded all the relevant deps so that we do not have any dep twice with different versions.

**Comment by benma** [comment]
bump

**Review by x1ddos — APPROVED** [review]
LGTM. Nice! Sorry for stalling.

**Pull request merged**
