### PR TITLE
releases: add v9.1.1

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Review by x1ddos — APPROVED** [review]
All hashes match.

```
$ gpg --verify releases/firmware-btc-v9.1.1/assertion-benma.sig releases/firmware-btc-v9.1.1/assertion.txt
gpg: Signature made Wed 19 Aug 2020 10:29:08 AM CEST
gpg:                using RSA key 2D8876810AB092E451DCA894804538928C37EAE8
gpg: Good signature from "Marko Bencun <marko@shiftcrypto.ch>" [ultimate]
gpg:                 aka "Marko Bencun <mbencun+pgp@gmail.com>" [ultimate]
Primary key fingerprint: 2260 E482 8888 2C76 AFAA  319D 67A2 B160 F74D B275
     Subkey fingerprint: 2D88 7681 0AB0 92E4 51DC  A894 8045 3892 8C37 EAE8

$ gpg --verify releases/firmware-v9.1.1/assertion-benma.sig releases/firmware-v9.1.1/assertion.txt
gpg: Signature made Wed 19 Aug 2020 10:28:28 AM CEST
gpg:                using RSA key 2D8876810AB092E451DCA894804538928C37EAE8
gpg: Good signature from "Marko Bencun <marko@shiftcrypto.ch>" [ultimate]
gpg:                 aka "Marko Bencun <mbencun+pgp@gmail.com>" [ultimate]
Primary key fingerprint: 2260 E482 8888 2C76 AFAA  319D 67A2 B160 F74D B275
     Subkey fingerprint: 2D88 7681 0AB0 92E4 51DC  A894 8045 3892 8C37 EAE8
```

LGTM

**Comment by TheCharlatan** [comment]
My btc firmware does not reproduce:

```
thecharlatan@thecharlatan  ~/bitbox02-firmware/releases 42ce5fc2 firmware-btc-only/v9.1.1 ? ⍟27: 
> sha256sum temp/build/bin/firmware-btc.bin  
   0a8eb97828fe1300d6f85b48cb4bf5f56c2dcdb5b0e8e7289217d0aa36dfde78  temp/build/bin/firmware-btc.bin
```

Diffoscope shows that the binary varies drastically from the one published here, so not sure what the cause is.

**Comment by x1ddos** [comment]
Did you use shiftcrypto/firmware_v2:18 docker dev image?

Did you have a clean working tree?

```
$ git status | grep 'working tree clean'
nothing to commit, working tree clean
```

**Comment by TheCharlatan** [comment]
The git tree is clean, I did not specify a specifically tagged docker image, just ran `./build.sh <version tag> <make command>` as the README states. Docker reports my bitbox02-firmware image to have been created a day ago, so I guess that is up to date.

**Comment by x1ddos** [comment]
> Docker reports my bitbox02-firmware image to have been created a day ago

that's your local dev enviroment, yes, but it should be created from `shiftcrypto/firmware_v2:18`. you can check which image you have with `docker images`.

**Comment by x1ddos** [comment]
> Diffoscope shows that the binary varies drastically from the one published here, so not sure what the cause is.

possible if you're using an older version of rust, I guess.

**Comment by benma** [comment]
> > Diffoscope shows that the binary varies drastically from the one published here, so not sure what the cause is.
> 
> possible if you're using an older version of rust, I guess.

It's docker, so that should all be fixed.

**Comment by x1ddos** [comment]
> It's docker, so that should all be fixed.

unless you're using and older docker image...

**Comment by benma** [comment]
> > It's docker, so that should all be fixed.
> 
> unless you're using an older docker image...

@x1ddos you should read the build.sh script. It builds the docker image from scratch.

**Comment by benma** [comment]
I am running it now again with building the image from scratch; let's see if I can reproduce the issue and if something in the Docker image changed recently.

If so, we should get into the habit of building the release from a newly made docker image instead of just the latest one.

**Comment by x1ddos** [comment]
> > > It's docker, so that should all be fixed.
> > 
> > 
> > unless you're using an older docker image...
> 
> @x1ddos you should read the build.sh script. It builds the docker image from scratch.

Ah, true. Sorry. It starts from Ubuntu 18.04 in https://github.com/digitalbitbox/bitbox02-firmware/blob/1726a1f6d0232e6d9aac385f6fd87685a83da379/Dockerfile#L17. I was stuck at the dev environment.

**Comment by benma** [comment]
@TheCharlatan my build from scratch using :

`./build.sh firmware-btc-only/v9.1.1 "make firmware-btc"`

finished. 

I get the expected hash, `d90c76701fde460b3bd01c0faff09c199796e48d401be8da5f81041f02fb72d3`.

Not sure why it would be different for you. Maybe just try again? What is the exact command you used?

**Comment by TheCharlatan** [comment]
Exact command as posted above: `/build.sh firmware-btc-only/v9.0.0 "make firmware-btc"`. I just ran it again checked out 42ce5fc2, all docker images removed before, and again sha256sum is `0a8eb97828fe1300d6f85b48cb4bf5f56c2dcdb5b0e8e7289217d0aa36dfde78`. The multi firmware reproduces nicely btw.

**Comment by benma** [comment]
It is 9.1.1, not 9.0.0 At least that hash matches :joy:

**Comment by TheCharlatan** [comment]
Ah, great, let me dig my own hole again :D

**Pull request merged**
