### PR TITLE
Signature for Jonathan Cross repro build assertion

### PR DESCRIPTION
**Pull request by jonathancross**
I have built the bitbox02 firmware and the result matches the checksum in [assertion.txt](https://github.com/digitalbitbox/bitbox02-firmware/blob/27dd2e859be0fbc2fbe6cddc85da4cc5a39111d7/releases/firmware-v4.1.0/assertion.txt). 
`47fc9ef2ff754455e350606de2ba5684b634455bd52ac12ba6a9fb792f5c229c`

### CODE REVIEW

**Comment by benma** [comment]
Awesome, thanks!

Please also add your pubkey here:
https://github.com/digitalbitbox/bitbox02-firmware/tree/master/releases/pubkeys

(described at the bottom [here](https://github.com/digitalbitbox/bitbox02-firmware/tree/master/releases#how-to-reproduce))

**Comment by jonathancross** [comment]
Done  :-)

**Comment by benma** [comment]
Merci!

If you are up to it, do the same for the BTC-only firmware :smile: 

https://github.com/digitalbitbox/bitbox02-firmware/tree/master/releases/firmware-btc-v4.1.0

**Comment by jonathancross** [comment]
> If you are up to it, do the same for the BTC-only firmware 😄

https://github.com/digitalbitbox/bitbox02-firmware/pull/138 :-)

**Pull request merged**
