### PR TITLE
py: The protobufs have become out of sync

### PR DESCRIPTION
**Pull request by NickeZ**

### CODE REVIEW

**Comment by benma** [comment]
Is this due to an update in the generator, or something else?

**Comment by NickeZ** [comment]
Don't know, Is it different when you compile it in your docker container?

**Comment by benma** [comment]
I pulled shiftcrypto/firmware_v2:7, did `make clean; make firmware`, and did not get any modified files. When I re-ran this after deleting all the Python protobuf files, I did get similar modifications.

So it seems like a small issue with the cmake files, probably the files should be generated every time.

**Comment by NickeZ** [comment]
Did you do `touch messages/hww.proto` or something like this? git might checkout the python files with younger dates than the proto files. Nothing Make can do about it..

**Comment by benma** [comment]
> Did you do `touch messages/hww.proto` or something like this? git might checkout the python files with younger dates than the proto files. Nothing Make can do about it..

No I didn't. I see that could be the issue. 

I don't even see where the Python protobuf generator is installed, or if/how it was updated so that the files change. Anyway, it's not a big deal :P

**Pull request merged**
