### PR TITLE
device-tests build-system: disable semihosting by default

### PR DESCRIPTION
**Pull request by NickeZ**
You can enable semihosting for the tests with `cmake -DSEMIHOSTING=ON ..`

I've gotten bitten by this a few times. I think it makes sense to have semihosting opt-in for the device tests / demos.

### CODE REVIEW

**Comment by NickeZ** [comment]
Since we made a new directory `build-semihosting` for semihosting builds, I definitely think this can be merged.

**Comment by x1ddos** [comment]
> I've gotten bitten by this a few times. I think it makes sense to have semihosting opt-in for the device tests / demos.

Bitten by what?

**Comment by NickeZ** [comment]
Device stops with black screen unless you have gdb connected with semihosting.

**Comment by x1ddos** [comment]
> Device stops with black screen unless you have gdb connected with semihosting.

Ah, good to know!

**Comment by NickeZ** [comment]
The changes in this PR was already partly applied. I still think the part that is left is necessary to apply for it to work correctly. According to [this readme](https://github.com/cbiffle/gcc-arm-embedded/blob/master/readme.txt) for example, the `--specs` flags must be applied to the linking step as well.

**Comment by benma** [comment]
Device-tests don't exist anymore.

**Pull request closed without merging**
