### PR TITLE
rust: update toolchain to 1.50.0

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by x1ddos** [comment]
Interesting:

```
 /usr/local/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld: 
  ../bin/bootloader-development.elf section `.relocate' will not fit in region `rom'
/usr/local/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld:
  region `rom' overflowed by 2436 bytes
collect2: error: ld returned 1 exit status
```

**Comment by benma** [comment]
Yeah very! The firmware binary also increased by a few hundred bytes 🤨

**Comment by x1ddos** [comment]
I looked at all release notes between 1.47 and 1.50 on https://github.com/rust-lang/rust/blob/master/RELEASES.md but didn't catch anything related. I either missed it or maybe it's somehow related to nostd.

**Comment by benma** [comment]
1.51.0 is already out - will try that before digging into it, maybe it is already fixed

**Comment by benma** [comment]
Closed in favour of https://github.com/digitalbitbox/bitbox02-firmware/pull/740

**Comment by NickeZ** [comment]
The size difference is likely due to changing versions of llvm. The optimisations passes have a big influence.

**Pull request closed without merging**
